x = int(4)
#Nur die Ausgaben ohne den Textbums
if((x < 9)&(x >= -5)):print(bool(True))
else:print(bool(False))
if((x < 4)|(x <= 4)):print(bool(True))
else:print(bool(False))
if(~( x < 5 & x < 10)):print(bool(True))
else:print(bool(False))
if((x*2 < 10)&(x+6 == 10)):print(bool(True))
else:print(bool(False))
if(x == ~x):print(bool(True))
else:print(bool(False))
if((x % 2 == 1)&(x % 3 == 1)):print(bool(True))
else:print(bool(False))